[package]
name = "ets"
version = "0.1.0"
authors = ["William Speirs <wspeirs@datto.com>"]

[dependencies]
clap = {version = "2.32"}
log = "0.4"
simplelog = "0.5"
walkdir = "2.2"
sha2 = "0.7"
digest = {version = "0.7", features = ["std"]}
globset = "0.4"
yaml-rust = "0.4"
